//! Phase 2 gate, assertion 7: this phase changes the score and not the picture.
//!
//! Phase 2 is the one phase that produces no observable — five pure scoring
//! functions with no path to the renderer — so the way to check it did not
//! quietly produce one is to pin the output byte-for-byte against a baseline
//! written *before* it.
//!
//! The baseline is a committed golden file, generated by the `llika` binary at
//! this phase's base commit. The existing cross-process test cannot serve as
//! the "before": it compares two runs of the same build, so it asserts
//! stability rather than invariance across a change.
//!
//! **Retired at Phase 3**, which is the phase that legitimately changes the
//! picture.

mod common;

use common::{fixture_path, sample};
use llika_core::{LayoutParams, RenderParams, build_schematic_svg};

#[test]
fn the_fixtures_svg_is_byte_identical_to_the_phase_one_golden() {
    let golden_path = fixture_path("golden/sample_network_phase1.svg");
    let golden = std::fs::read_to_string(&golden_path).unwrap_or_else(|e| {
        panic!(
            "the golden file at {} is readable: {e}",
            golden_path.display()
        )
    });

    // Every parameter at its default, which is how the binary was invoked to
    // write the golden — `build_schematic_svg` takes the identical path.
    let svg = build_schematic_svg(
        &sample(),
        &LayoutParams::default(),
        &RenderParams::default(),
    )
    .expect("the fixture is valid");

    assert_eq!(
        svg, golden,
        "the SVG changed in a phase that must not change it"
    );
}
