//! Phase 5 gate, assertion 1: `bundle_spacing: Some(0.0)` reproduces the
//! unbundled SVG byte-for-byte.
//!
//! **The capture point is the whole assertion.** Unlike Phase 3's
//! `iterations = 0` and Phase 4's `cluster_moves: false`, both computable at
//! test time from two public calls, the "before" here stopped existing the
//! moment `line_path_data` was replaced — and nothing in the tree held it,
//! since Phase 2's golden retired at Phase 3 by design. A golden captured
//! *after* the new renderer landed would assert only that the code agrees with
//! itself.
//!
//! So the baseline is a committed file, generated by the `llika` binary at this
//! phase's base commit with `--input` and `--output` alone, and committed as
//! this phase's first commit. Unlike the Phase 1 golden it does not retire:
//! "no bundling" is a picture that must never change again, which is the role
//! `PHASE3_POSITIONS` plays one subsystem over.

mod common;

use common::{fixture_path, sample};
use llika_core::{LayoutParams, RenderParams, build_schematic_svg};

fn golden() -> String {
    let path = fixture_path("golden/sample_network_unbundled.svg");
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("the golden file at {} is readable: {e}", path.display()))
}

fn render(render_params: &RenderParams) -> String {
    build_schematic_svg(&sample(), &LayoutParams::default(), render_params)
        .expect("the fixture is valid")
}

/// Assertion 1. The equivalence being asserted is that `Some(0.0)` **is** the
/// pre-Phase-5 default: the binary that wrote the golden had no
/// `bundle_spacing` field at all, so every other parameter here takes the same
/// default it took then, and zero spacing is what "no bundling" means.
#[test]
fn zero_bundle_spacing_reproduces_the_unbundled_svg() {
    let svg = render(&RenderParams {
        bundle_spacing: Some(0.0),
        ..RenderParams::default()
    });

    assert_eq!(
        svg,
        golden(),
        "zero spacing must draw exactly what the renderer drew before bundling existed"
    );
}

/// Assertion 6's premise, asserted rather than assumed.
///
/// Cross-process determinism is delegated to `llika-cli/tests/byte_stability.rs`,
/// which runs the binary twice **at the defaults**. That only covers this phase
/// if the defaults actually bundle — and `bundle_spacing: None` deriving
/// `stroke_width` is exactly the sort of thing that can be silently inert. This
/// is the check that it is not: at the defaults the picture must differ from the
/// unbundled one.
#[test]
fn the_default_parameters_actually_bundle() {
    assert_ne!(
        render(&RenderParams::default()),
        golden(),
        "the defaults draw the unbundled picture, so nothing downstream tests bundling"
    );
}
