//! Phase 5's gate, assertion 1: the streaming reader writes the same file the
//! whole-reading one did, on both committed feeds.
//!
//! **The capture point is the whole assertion**, which is why these two files
//! exist at all. Phase 5 changes how `stop_times.txt` is read and nothing about
//! what is drawn, so the load-bearing claim is that no byte moves — and the tree
//! held no expected network file for either feed, so "the files they produce now"
//! had no referent. The goldens are generated by the `llika-gtfs` binary at this
//! phase's **base commit** and landed as its first commit, before a line of the
//! reader changed. A golden captured afterwards would assert only that the code
//! agrees with itself. It is `llika-core/tests/golden.rs`'s idiom, and its
//! argument.
//!
//! A one-off pre/post diff would have been the cheaper answer and is refused: it
//! leaves the phase's load-bearing assertion out of the suite, and cannot be
//! reproduced by a second person once the change has landed.
//!
//! Unlike `llika-core`'s Phase 1 golden these do not retire. They are the standing
//! statement that the importer's output is a property of the feed rather than of
//! how the feed is read.

mod common;

use std::path::{Path, PathBuf};

use common::feed_dir;
use llika_gtfs::{ImportParams, import, to_json};

fn golden(name: &str) -> String {
    let path = fixtures().join("golden").join(name);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("the golden file at {} is readable: {e}", path.display()))
}

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// The bytes the binary writes, without shelling out for them: `main.rs:run` is
/// `import` then `to_json` then `fs::write`, and `to_json` lives in the library
/// for exactly this.
///
/// **At `ImportParams::default()`**, and that is stated rather than incidental.
/// `gallery/README.md` documents BART as `--route-types 1` while
/// `real_feed.rs:import_bart` uses the default; today both select the same twelve
/// routes, but a refreshed feed carrying a `route_type = 0` route would split the
/// golden from the test that reads it, for a reason nobody would look for.
fn imported(path: &Path) -> String {
    let (schema, _) = import(path, &ImportParams::default())
        .unwrap_or_else(|e| panic!("{} imports: {e}", path.display()));
    to_json(&schema).expect("the schema serialises")
}

#[test]
fn the_fixture_feed_imports_to_the_committed_golden() {
    assert_eq!(
        imported(&feed_dir()),
        golden("fixture.json"),
        "the fixture's imported network moved"
    );
}

/// The one that carries the phase. BART is the only feed here whose
/// `stop_times.txt` is large enough for the archive branch to be doing real work
/// — 2.7 MB and 57,188 rows against the fixture's 48.
///
/// **This pins the import to a third-party snapshot that expires.**
/// `tests/fixtures/bart.md` says so and names this file among the literals a
/// refresh moves: a refreshed feed can fail this with nothing wrong in the code.
#[test]
fn the_bart_feed_imports_to_the_committed_golden() {
    assert_eq!(
        imported(&fixtures().join("bart.zip")),
        golden("bart.json"),
        "BART's imported network moved"
    );
}

/// Phase 6's gate 1, second half — and it is the half that pins the committed
/// network rather than merely sizing it.
///
/// **Stated because the two are easily conflated.** `mbta_feed.rs`'s counts say
/// the importer produced *a* network of 119 stations and 8 lines; only
/// `to_json(&schema)` compared byte for byte against the committed file says it
/// produced *that* one. Three gates read `golden/mbta.json` — it draws, it scores
/// at four weightings, and it is what `gallery/mbta.svg` is regenerated from — so
/// without this assertion the whole product of OQ-8's second half is never
/// checked against the importer at all.
///
/// **Unlike the two above, this one needs a feed that is not in the tree**, which
/// is the same OQ-8 decision from the other side: the archive is fetched and
/// `.gitignore`d, so the test says how to get it rather than failing without it.
#[test]
#[cfg_attr(
    not(mbta_feed),
    ignore = "fetch https://cdn.mbta.com/MBTA_GTFS.zip to llika-gtfs/tests/fixtures/mbta.zip"
)]
fn the_mbta_feed_imports_to_the_committed_golden() {
    assert_eq!(
        imported(&fixtures().join("mbta.zip")),
        golden("mbta.json"),
        "MBTA's imported network moved"
    );
}
